### ISSUE TITLE
Hi Your API doesn't work for BTC TestNet

### ISSUE THREAD

**Issue by serhiy1017** [blockcypher/documentation#8]
https://blockstream.info/testnet/address/mqcrCFuhatZBerrNMrGcuNyFqez2YEaC5E
https://live.blockcypher.com/btc-testnet/address/mqcrCFuhatZBerrNMrGcuNyFqez2YEaC5E/

Could you check above link please?

My testnet address has transactions but it doesn't show any through your API now

**Comment by quentinlesceller** [comment]
Hi @serhiy1017 ,

We had some issues yesterday with the Bitcoin Testnet APIs. Everything is now fixed. Thank you for your patience.
Follow https://status.blockcypher.com/ for live updates.
